[package]
name = "gnss-rtk"
version = "0.6.0"
license = "MPL-2.0"
authors = ["Guillaume W. Bres <guillaume.bressaix@gmail.com>"]
description = "GNSS position solver"
homepage = "https://github.com/rtk-rs/gnss-rtk"
repository = "https://github.com/rtk-rs/gnss-rtk"
keywords = ["timing", "positioning", "gps", "glonass", "galileo"]
categories = ["science", "science::geo"]
edition = "2021"
readme = "README.md"

[features]
serde = [
    "dep:serde",
    "gnss-rs/serde",
    "hifitime/serde",
]

[dependencies]
log = "0.4"
thiserror = "1"
map_3d = "0.1.5"
polyfit-rs = "0.2"
nalgebra = "0.32.3"
itertools = "0.12.0"

gnss-rs = "2.2.1"
nyx-space = "2.0.0-rc"
anise = { version = "0.4.2", features = ["embed_ephem"] }
hifitime = { version = "4.0.0-alpha", features = ["std"] }
serde = { version = "1.0", optional = true, default-features = false, features = ["derive"] }

[dev-dependencies]
serde_json = "1"
serde = { version = "1", default-features = false, features = ["derive"] }

[[example]]
name = "ppp"
required-features = ["serde"]
