name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build & Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build
    - name: Build (All features)
      run: cargo build --all-features
    - name: Tests
      run: cargo test --all-features
  ppp:
    name: PPP
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build PPP
      run: |
        cargo build --release --all-features --example ppp
        export RUST_LOG=trace
    - name: SPP LSQ 1 Day Survey
      run: ./target/release/examples/ppp -c tests/survey/spp_lsq_1day.json
